### ISSUE TITLE
Sugestão de reports /heroes

### ISSUE THREAD

**Issue by mgramelich** [vin350/bombcrypto-bot#9]
Além das atuais opções de enviar print do mapa/print/bcoin, poderia adicionar tb enviar um print da tela de heróis, pra ver +- como tá o status de cada herói.

**Comment by vin350** [comment]
> 

gostei da ideia vou implementar no futuro

**Comment by Denver3D** [comment]
why there is an exe with the project that inject in \\?\C:\Windows\system32\wbem\WMIADAP.EXE  ? and it connect to this ip 8.240.191.254:80 (TCP)
